name: "Subtitle Extract"
guid: "CD893C24-B59E-4060-87B2-184070E1BF68"
imageUrl: "https://repo.jellyfin.org/releases/plugin/images/jellyfin-plugin-subtitleextract.png"
version: 7
targetAbi: "10.11.2.0"
framework: "net9.0"
owner: "jellyfin"
overview: "Extracts Subtitles."
description: >
  Extracts embedded subtitles.

category: "Subtitles"
artifacts:
  - "Jellyfin.Plugin.SubtitleExtract.dll"
changelog: |-
  - Fix HasChanged checks (#57) @Shadowghost
